### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by huluohu** [KonghaYao/chinese-poetry-index#1]
开发者你好，我用你的代码跑起来了，但是打开后什么都没有，请问如何使用，谢谢！
<img width="1225" alt="image" src="https://github.com/KonghaYao/chinese-poetry-index/assets/7138642/fe88815f-1638-4a3d-84c1-8fc56afd785d">

**Comment by KonghaYao** [comment]
这个没有数据应该是没有进行 pnpm upload

**Comment by huluohu** [comment]
感谢回复，后来重新跑了一次可以了。顺便说下哈，那个古诗词数据库最近更新了，文件夹名字都改成中文了。---- 回复的原邮件 ***@***.***>发送日期2023年11月24日 20:04 ***@***.***> ***@***.***>***@***.***>主题Re: [KonghaYao/chinese-poetry-index] 如何使用 (Issue #1)
这个没有数据应该是没有进行 pnpm upload

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/KonghaYao/chinese-poetry-index/issues/1#issuecomment-1825579112",
"url": "https://github.com/KonghaYao/chinese-poetry-index/issues/1#issuecomment-1825579112",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by KonghaYao** [comment]
近几日会更新一下，顺便把以前的数据加上和规范一下操作文档，感谢您的反馈 😉 @huluohu

**Comment by KonghaYao** [comment]
您好，已同步最新版本的 chinese-poetry，部署脚本也已经更改测试完毕了，您可以试试 @huluohu

**Comment by huluohu** [comment]
> 您好，已同步最新版本的 chinese-poetry，部署脚本也已经更改测试完毕了，您可以试试 @huluohu

好的，感谢感谢！
